package com.album.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNews<M extends BaseNews<M>> extends Model<M> implements IBean {

	public void setNewsId(java.lang.Long newsId) {
		set("news_id", newsId);
	}

	public java.lang.Long getNewsId() {
		return get("news_id");
	}

	public void setPublicId(java.lang.Long publicId) {
		set("public_id", publicId);
	}

	public java.lang.Long getPublicId() {
		return get("public_id");
	}

	public void setPublicName(java.lang.String publicName) {
		set("public_name", publicName);
	}

	public java.lang.String getPublicName() {
		return get("public_name");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setLikeNum(java.lang.Integer likeNum) {
		set("like_num", likeNum);
	}

	public java.lang.Integer getLikeNum() {
		return get("like_num");
	}

	public void setAuthority(java.lang.Integer authority) {
		set("authority", authority);
	}

	public java.lang.Integer getAuthority() {
		return get("authority");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
	}

	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public void setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

}
