package com.album.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("album", "album_id", Album.class);
		arp.addMapping("album_link_photo", "id", AlbumLinkPhoto.class);
		arp.addMapping("character", "character_id", Character.class);
		arp.addMapping("collect_photo", "collect_photo_id", CollectPhoto.class);
		arp.addMapping("comment", "comment_id", Comment.class);
		arp.addMapping("favorite", "favorite_id", Favorite.class);
		arp.addMapping("follow", "follow_id", Follow.class);
		arp.addMapping("news", "news_id", News.class);
		arp.addMapping("news_circle_timeline", "id", NewsCircleTimeline.class);
		arp.addMapping("photo", "photo_id", Photo.class);
		arp.addMapping("reply", "reply_id", Reply.class);
		arp.addMapping("thumb_up", "thumb_up_id", ThumbUp.class);
		arp.addMapping("user", "user_id", User.class);
	}
}

