package com.album.model;

import com.album.model.base.BaseAlbum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Album extends BaseAlbum<Album> {
	public static final Album dao = new Album().dao();
}
