package com.album.model;

import com.album.model.base.BaseAlbumLinkPhoto;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AlbumLinkPhoto extends BaseAlbumLinkPhoto<AlbumLinkPhoto> {
	public static final AlbumLinkPhoto dao = new AlbumLinkPhoto().dao();
}
