package com.album.model;

import com.album.model.base.BaseCharacter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Character extends BaseCharacter<Character> {
	public static final Character dao = new Character().dao();
}
