package com.album.model;

import com.album.model.base.BaseCollectPhoto;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CollectPhoto extends BaseCollectPhoto<CollectPhoto> {
	public static final CollectPhoto dao = new CollectPhoto().dao();
}
