package com.album.model;

import com.album.model.base.BaseFavorite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Favorite extends BaseFavorite<Favorite> {
	public static final Favorite dao = new Favorite().dao();
}
