package com.album.model;

import com.album.model.base.BaseNewsCircleTimeline;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsCircleTimeline extends BaseNewsCircleTimeline<NewsCircleTimeline> {
	public static final NewsCircleTimeline dao = new NewsCircleTimeline().dao();
}
