package com.album.model;

import com.album.model.base.BaseReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reply extends BaseReply<Reply> {
	public static final Reply dao = new Reply().dao();
}
