package com.album.model;

import com.album.model.base.BaseThumbUp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ThumbUp extends BaseThumbUp<ThumbUp> {
	public static final ThumbUp dao = new ThumbUp().dao();
}
