package com.album.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAlbumLinkPhoto<M extends BaseAlbumLinkPhoto<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setAlbumId(java.lang.Long albumId) {
		set("album_id", albumId);
	}

	public java.lang.Long getAlbumId() {
		return get("album_id");
	}

	public void setPhotoId(java.lang.Long photoId) {
		set("photo_id", photoId);
	}

	public java.lang.Long getPhotoId() {
		return get("photo_id");
	}

	public void setPhotoUrl(java.lang.String photoUrl) {
		set("photo_url", photoUrl);
	}

	public java.lang.String getPhotoUrl() {
		return get("photo_url");
	}

	public void setMarkTime(java.util.Date markTime) {
		set("mark_time", markTime);
	}

	public java.util.Date getMarkTime() {
		return get("mark_time");
	}

	public void setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
	}

	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

}
