package com.album.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReply<M extends BaseReply<M>> extends Model<M> implements IBean {

	public void setReplyId(java.lang.Long replyId) {
		set("reply_id", replyId);
	}

	public java.lang.Long getReplyId() {
		return get("reply_id");
	}

	public void setCommentId(java.lang.Long commentId) {
		set("comment_id", commentId);
	}

	public java.lang.Long getCommentId() {
		return get("comment_id");
	}

	public void setRelpyerId(java.lang.Long relpyerId) {
		set("relpyer_id", relpyerId);
	}

	public java.lang.Long getRelpyerId() {
		return get("relpyer_id");
	}

	public void setReplyerName(java.lang.String replyerName) {
		set("replyer_name", replyerName);
	}

	public java.lang.String getReplyerName() {
		return get("replyer_name");
	}

	public void setReplyContent(java.lang.String replyContent) {
		set("reply_content", replyContent);
	}

	public java.lang.String getReplyContent() {
		return get("reply_content");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
	}

	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public void setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

}
