package com.album.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewsCircleTimeline<M extends BaseNewsCircleTimeline<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setNewsId(java.lang.Long newsId) {
		set("news_id", newsId);
	}

	public java.lang.Long getNewsId() {
		return get("news_id");
	}

	public void setIsOwn(java.lang.Integer isOwn) {
		set("is_own", isOwn);
	}

	public java.lang.Integer getIsOwn() {
		return get("is_own");
	}

	public void setNewsTime(java.util.Date newsTime) {
		set("news_time", newsTime);
	}

	public java.util.Date getNewsTime() {
		return get("news_time");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
	}

	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public void setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

}
