package com.album.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCharacter<M extends BaseCharacter<M>> extends Model<M> implements IBean {

	public void setCharacterId(java.lang.Long characterId) {
		set("character_id", characterId);
	}

	public java.lang.Long getCharacterId() {
		return get("character_id");
	}

	public void setPhotoId(java.lang.Long photoId) {
		set("photo_id", photoId);
	}

	public java.lang.Long getPhotoId() {
		return get("photo_id");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
	}

	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public void setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

}
