package com.album.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFollow<M extends BaseFollow<M>> extends Model<M> implements IBean {

	public void setFollowId(java.lang.Long followId) {
		set("follow_id", followId);
	}

	public java.lang.Long getFollowId() {
		return get("follow_id");
	}

	public void setBeFollowedId(java.lang.Long beFollowedId) {
		set("be_followed_id", beFollowedId);
	}

	public java.lang.Long getBeFollowedId() {
		return get("be_followed_id");
	}

	public void setBeFollewedName(java.lang.String beFollewedName) {
		set("be_follewed_name", beFollewedName);
	}

	public java.lang.String getBeFollewedName() {
		return get("be_follewed_name");
	}

	public void setFollowerId(java.lang.Long followerId) {
		set("follower_id", followerId);
	}

	public java.lang.Long getFollowerId() {
		return get("follower_id");
	}

	public void setFollowerName(java.lang.String followerName) {
		set("follower_name", followerName);
	}

	public java.lang.String getFollowerName() {
		return get("follower_name");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
	}

	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public void setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

}
