package com.album.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseThumbUp<M extends BaseThumbUp<M>> extends Model<M> implements IBean {

	public void setThumbUpId(java.lang.Long thumbUpId) {
		set("thumb_up_id", thumbUpId);
	}

	public java.lang.Long getThumbUpId() {
		return get("thumb_up_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setPublicName(java.lang.String publicName) {
		set("public_name", publicName);
	}

	public java.lang.String getPublicName() {
		return get("public_name");
	}

	public void setNewsId(java.lang.Long newsId) {
		set("news_id", newsId);
	}

	public java.lang.Long getNewsId() {
		return get("news_id");
	}

	public void setPublicId(java.lang.Long publicId) {
		set("public_id", publicId);
	}

	public java.lang.Long getPublicId() {
		return get("public_id");
	}

	public void setPhotoId(java.lang.Long photoId) {
		set("photo_id", photoId);
	}

	public java.lang.Long getPhotoId() {
		return get("photo_id");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
	}

	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public void setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

}
