package com.album.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFavorite<M extends BaseFavorite<M>> extends Model<M> implements IBean {

	public void setFavoriteId(java.lang.Long favoriteId) {
		set("favorite_id", favoriteId);
	}

	public java.lang.Long getFavoriteId() {
		return get("favorite_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setFavoriteTitle(java.lang.String favoriteTitle) {
		set("favorite_title", favoriteTitle);
	}

	public java.lang.String getFavoriteTitle() {
		return get("favorite_title");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
	}

	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public void setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

}
